import { spawn } from 'node:child_process'
import { existsSync, writeFileSync, unlinkSync } from 'node:fs'
import { join } from 'node:path'

export type BuildRunner = (
  cmd: string,
  args: string[],
  opts: { cwd: string; env: Record<string, string> },
) => Promise<{ code: number; output: string }>

// Spawn flyctl, tee its output to the user (so they see buildkit progress) AND capture it.
export const defaultBuildRunner: BuildRunner = (cmd, args, opts) =>
  new Promise((resolve) => {
    const child = spawn(cmd, args, { cwd: opts.cwd, env: opts.env, stdio: ['inherit', 'pipe', 'pipe'] })
    let output = ''
    child.stdout?.on('data', (b) => { const s = b.toString(); output += s; process.stdout.write(s) })
    child.stderr?.on('data', (b) => { const s = b.toString(); output += s; process.stderr.write(s) })
    child.on('error', (err) => resolve({ code: -1, output: `${output}\n${err.message}` }))
    child.on('close', (code) => resolve({ code: code ?? -1, output }))
  })

// buildkit prints "pushing manifest for registry.fly.io/<app>:<label>@sha256:<digest>" on push.
// Pin to the digest — the bare tag races on Fly's registry (MANIFEST_UNKNOWN); the digest always resolves.
export function parseImageDigest(output: string, flyApp: string): string | null {
  const m = output.match(/pushing manifest for registry\.fly\.io\/[^\s]+@(sha256:[0-9a-f]+)/)
  return m ? `registry.fly.io/${flyApp}@${m[1]}` : null
}

// Write a minimal stub fly.toml iff the dir has none (flyctl needs app config; a fresh app has no
// machines to derive it from). Region is build-config only — `--build-only` places no machines.
// Returns a cleanup callback the caller MUST run in finally; leaves a user's own fly.toml alone.
function ensureFlyTomlStub(dir: string, flyApp: string, port: number): () => void {
  const path = join(dir, 'fly.toml')
  if (existsSync(path)) return () => { /* user owns it */ }
  const stub =
    `# Auto-generated by firth for source deploy. Safe to delete.\n` +
    `app = "${flyApp}"\n` +
    `primary_region = "iad"\n\n` +
    `[build]\n\n` +
    `[http_service]\n` +
    `  internal_port = ${port}\n` +
    `  force_https = true\n`
  writeFileSync(path, stub, 'utf8')
  return () => { try { unlinkSync(path) } catch { /* best-effort */ } }
}

export async function flyctlBuildAndPush(
  opts: { dir: string; flyApp: string; imageLabel: string; token: string; port: number },
  run: BuildRunner = defaultBuildRunner,
): Promise<{ imageRef: string }> {
  const cleanup = ensureFlyTomlStub(opts.dir, opts.flyApp, opts.port)
  try {
    const { code, output } = await run(
      'flyctl',
      ['deploy', '--remote-only', '--build-only', '--push', '--app', opts.flyApp, '--image-label', opts.imageLabel, '--no-cache'],
      { cwd: opts.dir, env: { ...process.env, FLY_API_TOKEN: opts.token } as Record<string, string> },
    )
    if (code !== 0) throw new Error(`flyctl deploy --build-only failed (exit ${code}). See output above.`)
    const imageRef = parseImageDigest(output, opts.flyApp)
    if (!imageRef) throw new Error('flyctl build succeeded but no "pushing manifest" digest line was found — cannot determine the image. Re-run with FLY_LOG_LEVEL=debug.')
    return { imageRef }
  } finally {
    cleanup()
  }
}
